var modules =
[
    [ "CryptoCell AES-CCM APIs", "group__crys__aesccm.html", "group__crys__aesccm" ],
    [ "CryptoCell CHACHA APIs", "group__crys__chacha.html", "group__crys__chacha" ],
    [ "CryptoCell CHACHA-POLY APIs", "group__crys__chacha__poly.html", "group__crys__chacha__poly" ],
    [ "CryptoCell DH APIs", "group__crys__dh.html", "group__crys__dh" ],
    [ "CryptoCell EC 25519 curve APIs", "group__cryptocell__ec.html", "group__cryptocell__ec" ],
    [ "CryptoCell ECC APIs", "group__cryptocell__ecpki.html", "group__cryptocell__ecpki" ],
    [ "CryptoCell general base error codes", "group__crys__error.html", "group__crys__error" ],
    [ "CryptoCell HASH APIs", "group__crys__hash.html", "group__crys__hash" ],
    [ "CryptoCell HMAC Key Derivation APIs", "group__crys__hkdf.html", "group__crys__hkdf" ],
    [ "CryptoCell HMAC APIs", "group__crys__hmac.html", "group__crys__hmac" ],
    [ "CryptoCell Key Derivation APIs", "group__crys__kdf.html", "group__crys__kdf" ],
    [ "CryptoCell PKA group", "group__cryptocell__pka.html", "group__cryptocell__pka" ],
    [ "CryptoCell POLY APIs", "group__crys__poly.html", "group__crys__poly" ],
    [ "CryptoCell Random Generator APIs", "group__crys__rnd.html", "group__crys__rnd" ],
    [ "CryptoCell RSA APIs", "group__crys__rsa.html", "group__crys__rsa" ],
    [ "CryptoCell SRP APIs", "group__crys__srp.html", "group__crys__srp" ],
    [ "CryptoCell library basic APIs", "group__sns__silib.html", "group__sns__silib" ],
    [ "CryptoCell AES APIs", "group__ssi__aes.html", "group__ssi__aes" ],
    [ "CryptoCell PAL platform dependant compiler specific definitions", "group__ssi__pal__compiler.html", null ],
    [ "CryptoCell PAL platform dependant types", "group__ssi__pal__types.html", "group__ssi__pal__types" ],
    [ "Wi-Fi_API", "group___m_x___w_i_f_i.html", "group___m_x___w_i_f_i" ],
    [ "Baseband (BB) API", "group___b_b___a_p_i.html", "group___b_b___a_p_i" ],
    [ "Board initialization flags.", "group___b_s_p___b_o_a_r_d___i_n_i_t___f_l_a_g_s.html", "group___b_s_p___b_o_a_r_d___i_n_i_t___f_l_a_g_s" ],
    [ "stack layer that controls MAC layer underneath", "group___lo_ra_w_a_n.html", "group___lo_ra_w_a_n" ],
    [ "LoRa MAC layer implementation", "group___l_o_r_a_m_a_c.html", null ],
    [ "Public API", "group__mbed-os-public.html", "group__mbed-os-public" ],
    [ "Internal API", "group__mbed-os-internal.html", "group__mbed-os-internal" ],
    [ "Hal_ospi", "group__hal__ospi.html", "group__hal__ospi" ],
    [ "API version", "group__version.html", "group__version" ],
    [ "Library initialization", "group__initialization.html", "group__initialization" ],
    [ "Key management", "group__key__management.html", "group__key__management" ],
    [ "Key import and export", "group__import__export.html", "group__import__export" ],
    [ "Message digests", "group__hash.html", "group__hash" ],
    [ "Message authentication codes", "group___m_a_c.html", "group___m_a_c" ],
    [ "Symmetric ciphers", "group__cipher.html", "group__cipher" ],
    [ "Authenticated encryption with associated data (AEAD)", "group__aead.html", "group__aead" ],
    [ "Asymmetric cryptography", "group__asymmetric.html", "group__asymmetric" ],
    [ "Key derivation and pseudorandom generation", "group__key__derivation.html", "group__key__derivation" ],
    [ "Random generation", "group__random.html", "group__random" ],
    [ "Hardware-Accelerated Message Digests", "group__driver__digest.html", "group__driver__digest" ],
    [ "Hardware-Accelerated Message Authentication Code", "group__accel__mac.html", "group__accel__mac" ],
    [ "Hardware-Accelerated Block Ciphers", "group__accel__cipher.html", "group__accel__cipher" ],
    [ "Hardware-Accelerated Authenticated Encryption with Additional Data", "group__accel__aead.html", "group__accel__aead" ],
    [ "Hardware-Accelerated Asymmetric Cryptography", "group__accel__asymmetric.html", "group__accel__asymmetric" ],
    [ "Entropy Generation", "group__driver__rng.html", "group__driver__rng" ],
    [ "TLS helper functions", "group__psa__tls__helpers.html", null ],
    [ "Secure element driver initialization", "group__se__init.html", "group__se__init" ],
    [ "Secure Element Message Authentication Codes", "group__se__mac.html", "group__se__mac" ],
    [ "Secure Element Symmetric Ciphers", "group__se__cipher.html", "group__se__cipher" ],
    [ "Secure Element Asymmetric Cryptography", "group__se__asymmetric.html", "group__se__asymmetric" ],
    [ "Secure Element Authenticated Encryption with Additional Data", "group__se__aead.html", "group__se__aead" ],
    [ "Secure Element Key Management", "group__se__key__management.html", "group__se__key__management" ],
    [ "Secure Element Key Derivation and Agreement", "group__driver__derivation.html", "group__driver__derivation" ],
    [ "Secure element driver registration", "group__se__registration.html", "group__se__registration" ],
    [ "Error codes", "group__error.html", "group__error" ],
    [ "Key and algorithm types", "group__crypto__types.html", "group__crypto__types" ],
    [ "Key lifetimes", "group__key__lifetimes.html", "group__key__lifetimes" ],
    [ "Key policies", "group__policy.html", "group__policy" ],
    [ "Key attributes", "group__attributes.html", "group__attributes" ],
    [ "Key derivation", "group__derivation.html", "group__derivation" ],
    [ "Helper macros", "group__helper__macros.html", "group__helper__macros" ],
    [ "Cellular", "group__cellular.html", "group__cellular" ],
    [ "Netsocket", "group__netsocket.html", "group__netsocket" ],
    [ "Sl_crypto", "group__sl__crypto.html", "group__sl__crypto" ],
    [ "Buffer management", "group__group__bsp__network__buffer.html", "group__group__bsp__network__buffer" ],
    [ "WiFi Initialization", "group__group__bsp__wifi.html", "group__group__bsp__wifi" ],
    [ "WHD Event handling API", "group__event.html", "group__event" ],
    [ "WHD Buffer Interface API", "group__buffif.html", "group__buffif" ],
    [ "WHD Resource API", "group__res.html", "group__res" ],
    [ "WHD Wi-Fi API", "group__wifi.html", "group__wifi" ],
    [ "Wiced Resource Management API's", "group__resourceapi.html", "group__resourceapi" ],
    [ "Ble", "group__ble.html", "group__ble" ],
    [ "STACK_ATTS_API", "group___s_t_a_c_k___a_t_t_s___a_p_i.html", "group___s_t_a_c_k___a_t_t_s___a_p_i" ],
    [ "STACK_ATTC_API", "group___s_t_a_c_k___a_t_t_c___a_p_i.html", "group___s_t_a_c_k___a_t_t_c___a_p_i" ],
    [ "STACK_ATT_API", "group___s_t_a_c_k___a_t_t___a_p_i.html", "group___s_t_a_c_k___a_t_t___a_p_i" ],
    [ "STACK_INIT", "group___s_t_a_c_k___i_n_i_t.html", "group___s_t_a_c_k___i_n_i_t" ],
    [ "STACK_EVENT", "group___s_t_a_c_k___e_v_e_n_t.html", "group___s_t_a_c_k___e_v_e_n_t" ],
    [ "STACK_DM_API", "group___s_t_a_c_k___d_m___a_p_i.html", "group___s_t_a_c_k___d_m___a_p_i" ],
    [ "STACK_HCI_EVT_API", "group___s_t_a_c_k___h_c_i___e_v_t___a_p_i.html", "group___s_t_a_c_k___h_c_i___e_v_t___a_p_i" ],
    [ "STACK_HCI_CMD_API", "group___s_t_a_c_k___h_c_i___c_m_d___a_p_i.html", "group___s_t_a_c_k___h_c_i___c_m_d___a_p_i" ],
    [ "STACK_HCI_ACL_API", "group___s_t_a_c_k___h_c_i___a_c_l___a_p_i.html", "group___s_t_a_c_k___h_c_i___a_c_l___a_p_i" ],
    [ "STACK_HCI_INIT_API", "group___s_t_a_c_k___h_c_i___i_n_i_t___a_p_i.html", "group___s_t_a_c_k___h_c_i___i_n_i_t___a_p_i" ],
    [ "STACK_HCI_OPT_API", "group___s_t_a_c_k___h_c_i___o_p_t___a_p_i.html", "group___s_t_a_c_k___h_c_i___o_p_t___a_p_i" ],
    [ "STACK_HCI_API", "group___s_t_a_c_k___h_c_i___a_p_i.html", "group___s_t_a_c_k___h_c_i___a_p_i" ],
    [ "STACK_L2CAP_API", "group___s_t_a_c_k___l2_c_a_p___a_p_i.html", "group___s_t_a_c_k___l2_c_a_p___a_p_i" ],
    [ "STACK_SECURITY_API", "group___s_t_a_c_k___s_e_c_u_r_i_t_y___a_p_i.html", "group___s_t_a_c_k___s_e_c_u_r_i_t_y___a_p_i" ],
    [ "STACK_SMP_API", "group___s_t_a_c_k___s_m_p___a_p_i.html", "group___s_t_a_c_k___s_m_p___a_p_i" ],
    [ "GATT_AND_GAP_SERVICE", "group___g_a_t_t___a_n_d___g_a_p___s_e_r_v_i_c_e.html", "group___g_a_t_t___a_n_d___g_a_p___s_e_r_v_i_c_e" ],
    [ "PAL_BB_INIT", "group___p_a_l___b_b___i_n_i_t.html", "group___p_a_l___b_b___i_n_i_t" ],
    [ "PAL_BB_CLOCK", "group___p_a_l___b_b___c_l_o_c_k.html", "group___p_a_l___b_b___c_l_o_c_k" ],
    [ "PAL_BB_BLE_CHAN", "group___p_a_l___b_b___b_l_e___c_h_a_n.html", "group___p_a_l___b_b___b_l_e___c_h_a_n" ],
    [ "PAL_BB_BLE_DATA", "group___p_a_l___b_b___b_l_e___d_a_t_a.html", "group___p_a_l___b_b___b_l_e___d_a_t_a" ],
    [ "PAL_BB_BLE_INIT", "group___p_a_l___b_b___b_l_e___i_n_i_t.html", "group___p_a_l___b_b___b_l_e___i_n_i_t" ],
    [ "PAL_BB_BLE_TEST", "group___p_a_l___b_b___b_l_e___t_e_s_t.html", "group___p_a_l___b_b___b_l_e___t_e_s_t" ],
    [ "PAL_BUTTON", "group___p_a_l___b_u_t_t_o_n.html", "group___p_a_l___b_u_t_t_o_n" ],
    [ "PAL_CFG", "group___p_a_l___c_f_g.html", "group___p_a_l___c_f_g" ],
    [ "PAL_CODEC", "group___p_a_l___c_o_d_e_c.html", "group___p_a_l___c_o_d_e_c" ],
    [ "PAL_CRYPTO", "group___p_a_l___c_r_y_p_t_o.html", "group___p_a_l___c_r_y_p_t_o" ],
    [ "PAL_FLASH", "group___p_a_l___f_l_a_s_h.html", "group___p_a_l___f_l_a_s_h" ],
    [ "PAL_I2S", "group___p_a_l___i2_s.html", "group___p_a_l___i2_s" ],
    [ "PAL_IO_EXP", "group___p_a_l___i_o___e_x_p.html", "group___p_a_l___i_o___e_x_p" ],
    [ "PAL_LED", "group___p_a_l___l_e_d.html", null ],
    [ "PAL_RADIO", "group___p_a_l___r_a_d_i_o.html", "group___p_a_l___r_a_d_i_o" ],
    [ "PAL_RTC", "group___p_a_l___r_t_c.html", "group___p_a_l___r_t_c" ],
    [ "PAL_SPI", "group___p_a_l___s_p_i.html", "group___p_a_l___s_p_i" ],
    [ "PAL_SYS", "group___p_a_l___s_y_s.html", "group___p_a_l___s_y_s" ],
    [ "PAL_TIMER", "group___p_a_l___t_i_m_e_r.html", "group___p_a_l___t_i_m_e_r" ],
    [ "PAL_TWI", "group___p_a_l___t_w_i.html", "group___p_a_l___t_w_i" ],
    [ "PAL_TYPES", "group___p_a_l___t_y_p_e_s.html", null ],
    [ "PAL_UART", "group___p_a_l___u_a_r_t.html", "group___p_a_l___u_a_r_t" ],
    [ "WSF_UTIL_API", "group___w_s_f___u_t_i_l___a_p_i.html", "group___w_s_f___u_t_i_l___a_p_i" ],
    [ "WSF_ASSERT_API", "group___w_s_f___a_s_s_e_r_t___a_p_i.html", "group___w_s_f___a_s_s_e_r_t___a_p_i" ],
    [ "WSF_BUF_API", "group___w_s_f___b_u_f___a_p_i.html", "group___w_s_f___b_u_f___a_p_i" ],
    [ "WSF_BUF_IO_API", "group___w_s_f___b_u_f___i_o___a_p_i.html", "group___w_s_f___b_u_f___i_o___a_p_i" ],
    [ "WSF_CS_API", "group___w_s_f___c_s___a_p_i.html", "group___w_s_f___c_s___a_p_i" ],
    [ "WSF_EFS_API", "group___w_s_f___e_f_s___a_p_i.html", "group___w_s_f___e_f_s___a_p_i" ],
    [ "WSF_HEAP_API", "group___w_s_f___h_e_a_p___a_p_i.html", "group___w_s_f___h_e_a_p___a_p_i" ],
    [ "WSF_MATH_API", "group___w_s_f___m_a_t_h___a_p_i.html", "group___w_s_f___m_a_t_h___a_p_i" ],
    [ "WSF_MSG_API", "group___w_s_f___m_s_g___a_p_i.html", "group___w_s_f___m_s_g___a_p_i" ],
    [ "WSF_OS_API", "group___w_s_f___o_s___a_p_i.html", "group___w_s_f___o_s___a_p_i" ],
    [ "WSF_QUEUE_API", "group___w_s_f___q_u_e_u_e___a_p_i.html", "group___w_s_f___q_u_e_u_e___a_p_i" ],
    [ "WSF_TIMER_API", "group___w_s_f___t_i_m_e_r___a_p_i.html", "group___w_s_f___t_i_m_e_r___a_p_i" ],
    [ "WSF_TRACE_API", "group___w_s_f___t_r_a_c_e___a_p_i.html", "group___w_s_f___t_r_a_c_e___a_p_i" ],
    [ "WSF_TYPES", "group___w_s_f___t_y_p_e_s.html", null ],
    [ "BB_API_BLE_PDU_FILT", "group___b_b___a_p_i___b_l_e___p_d_u___f_i_l_t.html", "group___b_b___a_p_i___b_l_e___p_d_u___f_i_l_t" ],
    [ "BB_API_BLE_WL", "group___b_b___a_p_i___b_l_e___w_l.html", "group___b_b___a_p_i___b_l_e___w_l" ],
    [ "BB_API_BLE_RL", "group___b_b___a_p_i___b_l_e___r_l.html", "group___b_b___a_p_i___b_l_e___r_l" ],
    [ "LL_API_INIT", "group___l_l___a_p_i___i_n_i_t.html", "group___l_l___a_p_i___i_n_i_t" ],
    [ "LL_API_DEVICE", "group___l_l___a_p_i___d_e_v_i_c_e.html", "group___l_l___a_p_i___d_e_v_i_c_e" ],
    [ "LL_API_BROADCAST", "group___l_l___a_p_i___b_r_o_a_d_c_a_s_t.html", "group___l_l___a_p_i___b_r_o_a_d_c_a_s_t" ],
    [ "LL_API_OBSERVER", "group___l_l___a_p_i___o_b_s_e_r_v_e_r.html", "group___l_l___a_p_i___o_b_s_e_r_v_e_r" ],
    [ "LL_API_CONN", "group___l_l___a_p_i___c_o_n_n.html", "group___l_l___a_p_i___c_o_n_n" ],
    [ "LL_API_ISO", "group___l_l___a_p_i___i_s_o.html", "group___l_l___a_p_i___i_s_o" ],
    [ "LL_API_ENCRYPT", "group___l_l___a_p_i___e_n_c_r_y_p_t.html", "group___l_l___a_p_i___e_n_c_r_y_p_t" ],
    [ "LL_API_TEST", "group___l_l___a_p_i___t_e_s_t.html", "group___l_l___a_p_i___t_e_s_t" ],
    [ "LL_API_EVENT", "group___l_l___a_p_i___e_v_e_n_t.html", "group___l_l___a_p_i___e_v_e_n_t" ],
    [ "LL_API_CENTRAL", "group___l_l___a_p_i___c_e_n_t_r_a_l.html", "group___l_l___a_p_i___c_e_n_t_r_a_l" ],
    [ "LL_API_DATA", "group___l_l___a_p_i___d_a_t_a.html", "group___l_l___a_p_i___d_a_t_a" ],
    [ "LL_API_DIAG", "group___l_l___a_p_i___d_i_a_g.html", "group___l_l___a_p_i___d_i_a_g" ],
    [ "LL_API_CIS", "group___l_l___a_p_i___c_i_s.html", "group___l_l___a_p_i___c_i_s" ],
    [ "LL_INIT_API", "group___l_l___i_n_i_t___a_p_i.html", "group___l_l___i_n_i_t___a_p_i" ],
    [ "LL_LCTR_API", "group___l_l___l_c_t_r___a_p_i.html", "group___l_l___l_c_t_r___a_p_i" ],
    [ "LL_LCTR_API_ADV_MST", "group___l_l___l_c_t_r___a_p_i___a_d_v___m_s_t.html", "group___l_l___l_c_t_r___a_p_i___a_d_v___m_s_t" ],
    [ "LL_LCTR_API_ADV_SLV", "group___l_l___l_c_t_r___a_p_i___a_d_v___s_l_v.html", "group___l_l___l_c_t_r___a_p_i___a_d_v___s_l_v" ],
    [ "LL_LCTR_API_BIS", "group___l_l___l_c_t_r___a_p_i___b_i_s.html", "group___l_l___l_c_t_r___a_p_i___b_i_s" ],
    [ "LL_LCTR_API_CONN", "group___l_l___l_c_t_r___a_p_i___c_o_n_n.html", "group___l_l___l_c_t_r___a_p_i___c_o_n_n" ],
    [ "LL_LCTR_API_INIT_MST", "group___l_l___l_c_t_r___a_p_i___i_n_i_t___m_s_t.html", null ],
    [ "LL_LCTR_API_INIT_MST_AE", "group___l_l___l_c_t_r___a_p_i___i_n_i_t___m_s_t___a_e.html", "group___l_l___l_c_t_r___a_p_i___i_n_i_t___m_s_t___a_e" ],
    [ "LL_LCTR_API_PRIV", "group___l_l___l_c_t_r___a_p_i___p_r_i_v.html", "group___l_l___l_c_t_r___a_p_i___p_r_i_v" ],
    [ "LL_LCTR_API_SC", "group___l_l___l_c_t_r___a_p_i___s_c.html", null ],
    [ "LL_LMGR_API", "group___l_l___l_m_g_r___a_p_i.html", "group___l_l___l_m_g_r___a_p_i" ],
    [ "LL_LMGR_API_ADV_MST", "group___l_l___l_m_g_r___a_p_i___a_d_v___m_s_t.html", "group___l_l___l_m_g_r___a_p_i___a_d_v___m_s_t" ],
    [ "LL_LMGR_API_ADV_SLV", "group___l_l___l_m_g_r___a_p_i___a_d_v___s_l_v.html", "group___l_l___l_m_g_r___a_p_i___a_d_v___s_l_v" ],
    [ "LL_LMGR_API_CIS_MST", "group___l_l___l_m_g_r___a_p_i___c_i_s___m_s_t.html", "group___l_l___l_m_g_r___a_p_i___c_i_s___m_s_t" ],
    [ "LL_LMGR_API_CONN", "group___l_l___l_m_g_r___a_p_i___c_o_n_n.html", "group___l_l___l_m_g_r___a_p_i___c_o_n_n" ],
    [ "LL_LMGR_API_ISO", "group___l_l___l_m_g_r___a_p_i___i_s_o.html", "group___l_l___l_m_g_r___a_p_i___i_s_o" ],
    [ "LL_LMGR_API_PRIV", "group___l_l___l_m_g_r___a_p_i___p_r_i_v.html", "group___l_l___l_m_g_r___a_p_i___p_r_i_v" ],
    [ "LL_LMGR_API_SC", "group___l_l___l_m_g_r___a_p_i___s_c.html", "group___l_l___l_m_g_r___a_p_i___s_c" ],
    [ "LL_LHCI_INT", "group___l_l___l_h_c_i___i_n_t.html", "group___l_l___l_h_c_i___i_n_t" ],
    [ "Netinterface", "group__netinterface.html", "group__netinterface" ],
    [ "Nfc", "group__nfc.html", "group__nfc" ],
    [ "ACore", "group___a_core.html", "group___a_core" ],
    [ "NDEF", "group___n_d_e_f.html", "group___n_d_e_f" ],
    [ "Core", "group___core.html", "group___core" ],
    [ "Implementation", "group___implementation.html", "group___implementation" ],
    [ "Transceiver", "group___transceiver.html", null ],
    [ "Frameworks", "group__frameworks.html", "group__frameworks" ],
    [ "Hal", "group__hal.html", "group__hal" ],
    [ "PSA-Attestation", "group___p_s_a-_attestation.html", "group___p_s_a-_attestation" ],
    [ "Storage", "group__storage.html", null ],
    [ "Filesystem", "group__filesystem.html", "group__filesystem" ],
    [ "system", "group__file.html", "group__file" ]
];