var searchData=
[
  ['scheduler_0',['Scheduler',['../group__nfc-scheduler.html',1,'']]],
  ['scopedlock_20functions_1',['ScopedLock functions',['../group__platform___scoped_lock.html',1,'']]],
  ['secure_20element_20asymmetric_20cryptography_2',['Secure Element Asymmetric Cryptography',['../group__se__asymmetric.html',1,'']]],
  ['secure_20element_20authenticated_20encryption_20with_20additional_20data_3',['Secure Element Authenticated Encryption with Additional Data',['../group__se__aead.html',1,'']]],
  ['secure_20element_20driver_20initialization_4',['Secure element driver initialization',['../group__se__init.html',1,'']]],
  ['secure_20element_20driver_20registration_5',['Secure element driver registration',['../group__se__registration.html',1,'']]],
  ['secure_20element_20key_20derivation_20and_20agreement_6',['Secure Element Key Derivation and Agreement',['../group__driver__derivation.html',1,'']]],
  ['secure_20element_20key_20management_7',['Secure Element Key Management',['../group__se__key__management.html',1,'']]],
  ['secure_20element_20message_20authentication_20codes_8',['Secure Element Message Authentication Codes',['../group__se__mac.html',1,'']]],
  ['secure_20element_20symmetric_20ciphers_9',['Secure Element Symmetric Ciphers',['../group__se__cipher.html',1,'']]],
  ['semaphore_20class_10',['Semaphore class',['../group__rtos___semaphore.html',1,'']]],
  ['serial_20configuration_20functions_11',['Serial Configuration Functions',['../group__hal___general_serial.html',1,'']]],
  ['serial_20hal_20tests_12',['Serial hal tests',['../group__hal___general_serial__tests.html',1,'']]],
  ['serial_20rx_20events_20macros_13',['Serial RX Events Macros',['../group___serial_r_x_events.html',1,'']]],
  ['serial_20tx_20events_20macros_14',['Serial TX Events Macros',['../group___serial_t_x_events.html',1,'']]],
  ['serialbase_20class_15',['SerialBase class',['../group__drivers___serial_base.html',1,'']]],
  ['serialwireoutput_20class_16',['SerialWireOutput class',['../group__drivers___serial_wire_output.html',1,'']]],
  ['server_17',['Server',['../group__server.html',1,'']]],
  ['sfdp_18',['SFDP',['../group__drivers-internal-api-sfdp.html',1,'']]],
  ['sha_2d1_19',['SHA-1',['../group__mbedtls__sha1__module.html',1,'']]],
  ['sha_2d224_20and_20sha_2d256_20',['SHA-224 and SHA-256',['../group__mbedtls__sha256__module.html',1,'']]],
  ['sha_2d384_20and_20sha_2d512_21',['SHA-384 and SHA-512',['../group__mbedtls__sha512__module.html',1,'']]],
  ['singletonptr_20class_22',['SingletonPtr class',['../group__platform___singleton_ptr.html',1,'']]],
  ['sleep_20hal_20requirements_23',['sleep hal requirements',['../group__hal__sleep.html',1,'']]],
  ['sleep_20hal_20tests_24',['sleep hal tests',['../group__hal__sleep__tests.html',1,'']]],
  ['sleep_20manager_20api_25',['Sleep manager API',['../group__hal__sleep__manager.html',1,'']]],
  ['sleep_20manager_20api_20tests_26',['Sleep manager API tests',['../group__hal__sleep__manager__tests.html',1,'']]],
  ['span_20class_27',['Span class',['../group__platform___span.html',1,'']]],
  ['spi_28',['SPI',['../group__drivers-public-api-spi.html',1,'']]],
  ['spi_20class_29',['SPI class',['../group__drivers___s_p_i.html',1,'']]],
  ['spi_20configuration_20functions_30',['SPI Configuration Functions',['../group__hal___general_s_p_i.html',1,'']]],
  ['spi_20hal_20tests_31',['SPI hal tests',['../group__hal___general_s_p_i__tests.html',1,'']]],
  ['spislave_20class_32',['SPISlave class',['../group__drivers___s_p_i_slave.html',1,'']]],
  ['ssl_2ftls_33',['SSL/TLS',['../group__mbedtls__ssl__module.html',1,'']]],
  ['stats_20functions_34',['stats functions',['../group__platform__stats.html',1,'']]],
  ['storage_35',['Storage',['../group__storage.html',1,'']]],
  ['stream_20class_36',['Stream class',['../group__platform___stream.html',1,'']]],
  ['symmetric_20ciphers_37',['Symmetric ciphers',['../group__cipher.html',1,'']]],
  ['synchronous_20i2c_20hardware_20abstraction_20layer_20for_20slave_38',['Synchronous I2C Hardware Abstraction Layer for slave',['../group___synch_i2_c.html',1,'']]],
  ['synchronous_20spi_20hardware_20abstraction_20layer_39',['Synchronous SPI Hardware Abstraction Layer',['../group___synch_s_p_i.html',1,'']]],
  ['systimer_20class_40',['SysTimer class',['../group__mbed___sys_timer.html',1,'']]]
];
